
const $ = id => document.getElementById(id);
const defaultPosts = [
  {id:'p1', title:'Warm-up before lifting heavy', category:'Safety', summary:'Spend 6 to 10 minutes raising body temperature, mobilising the target joints and completing one light practice set before loading the bar.', date:'2026-01-01'},
  {id:'p2', title:'Protein timing made simple', category:'Nutrition', summary:'Hit your daily protein target first. Then spread protein across 3 to 5 meals for easier digestion and better training recovery.', date:'2026-01-02'},
  {id:'p3', title:'The best posture cue for beginners', category:'Workout', summary:'Before every rep, brace the core, keep the neck neutral and move slowly enough that the target muscle, not momentum, does the work.', date:'2026-01-03'}
];
function getPosts(){try{return JSON.parse(localStorage.getItem('hf_posts')) || defaultPosts}catch(e){return defaultPosts}}
function setPosts(posts){localStorage.setItem('hf_posts', JSON.stringify(posts))}
function renderBlogs(){const grid=$('blogGrid'); if(!grid) return; const posts=getPosts(); grid.innerHTML=posts.map(p=>`<article class="blog-card"><span class="tag">${p.category}</span><h3>${p.title}</h3><p class="muted">${p.summary}</p><small>${p.date || 'Today'}</small></article>`).join('') || '<p class="muted">No posts yet. Add one from Admin.</p>'}
function renderAdmin(){const list=$('adminPostList'); if(!list) return; const posts=getPosts(); list.innerHTML=posts.map(p=>`<div class="post-row"><div><b>${p.title}</b><br><small>${p.category} • ${p.date || ''}</small></div><div><button class="secondary" onclick="editPost('${p.id}')">Edit</button> <button class="danger" onclick="deletePost('${p.id}')">Delete</button></div></div>`).join('') || '<p class="muted">No posts published.</p>'}
function savePost(){const title=$('postTitle').value.trim(), category=$('postCategory').value, summary=$('postSummary').value.trim(), id=$('postId').value || 'p'+Date.now(); if(!title||!summary){$('adminMsg').textContent='Please enter title and summary.'; return} const posts=getPosts().filter(p=>p.id!==id); posts.unshift({id,title,category,summary,date:new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}); setPosts(posts); resetPostForm(); $('adminMsg').textContent='Post published successfully.'; renderAdmin(); renderBlogs()}
function editPost(id){const p=getPosts().find(x=>x.id===id); if(!p) return; $('postId').value=p.id; $('postTitle').value=p.title; $('postCategory').value=p.category; $('postSummary').value=p.summary; $('adminMsg').textContent='Editing existing post.'; scrollTo({top:0,behavior:'smooth'})}
function deletePost(id){setPosts(getPosts().filter(p=>p.id!==id)); renderAdmin(); renderBlogs()}
function resetPostForm(){['postId','postTitle','postSummary'].forEach(i=>{if($(i)) $(i).value=''}); if($('postCategory')) $('postCategory').value='Workout'}
function saveExercise(name){const key='hf_saved_exercises'; const arr=JSON.parse(localStorage.getItem(key)||'[]'); if(!arr.includes(name)) arr.push(name); localStorage.setItem(key,JSON.stringify(arr)); alert(name+' saved to your browser list.');}
function calcBMI(){const w=+$('weight').value,h=+$('height').value/100;if(!w||!h)return $('bmiResult').textContent='Enter valid weight and height.';const bmi=w/(h*h);const cat=bmi<18.5?'Underweight':bmi<25?'Normal':bmi<30?'Overweight':'Obese';$('bmiResult').textContent=`BMI: ${bmi.toFixed(1)}\nCategory: ${cat}\nTip: Use BMI as a broad screening number, not a final fitness diagnosis.`}
function calcCalories(){const w=+$('calWeight').value,g=$('goal').value;if(!w)return $('calResult').textContent='Enter weight.';let c=w*30;if(g==='Fat Loss')c-=400;if(g==='Muscle Gain')c+=350;$('calResult').textContent=`Goal: ${g}\nEstimated Calories: ${Math.round(c)} kcal/day\nProtein: ${Math.round(w*1.6)}g - ${Math.round(w*2)}g/day`}
function calcWater(){const w=+$('waterWeight').value;if(!w)return $('waterResult').textContent='Enter weight.'; $('waterResult').textContent=`Water Target: ${(w*.035).toFixed(1)} liters/day\nIncrease slightly on hot days or high-sweat training days.`}
function makeSplit(){const l=$('level').value;const s={Beginner:'Full Body - 3 days/week\nWalk + mobility on rest days',Intermediate:'Push / Pull / Legs / Upper / Lower',Advanced:'Push Heavy / Pull Heavy / Legs / Push Volume / Pull Volume / Legs + Core'};$('splitResult').textContent=`${l} Split\n${s[l]}`}
function recoveryScore(){const sleep=+$('sleep').value,sore=+$('sore').value;if(!sleep||!sore)return $('recoveryResult').textContent='Enter sleep and soreness.';let score=Math.max(10,Math.min(100,(sleep*12)-(sore*5)+45));$('recoveryResult').textContent=`Recovery Score: ${Math.round(score)}/100\n${score>70?'Good day for planned training.':score>45?'Train lighter and extend warm-up.':'Prioritise recovery, mobility and sleep.'}`}
function proteinTarget(){const w=+$('proteinWeight').value;if(!w)return $('proteinResult').textContent='Enter weight.';$('proteinResult').textContent=`Daily Protein Target: ${Math.round(w*1.6)}g - ${Math.round(w*2.2)}g\nSpread across meals for easier consistency.`}
document.addEventListener('DOMContentLoaded',()=>{renderBlogs();renderAdmin()});
